/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface TodoCreateInput {
  dueDate: Date;
  title: string;
}

export interface TodoSearchInput {
  filterBy?: {
    completed?: boolean;
  };
  searchBy?: {
    id?: number;
    title?: string;
  };
  sortBy?: {
    createdAt?: "asc" | "desc";
    dueDate?: "asc" | "desc";
  };
}
